package main

var EwalletChannelCodes = []string{
	"DANA",
	"OVO",
	"LINKAJA",
	"SHOPEEPAY",
	"SAKUKU",
	"ASTRAPAY",
	"JENIUSPAY",
}
var VirtualAccountChannelCodes = []string{
	"BCA_VIRTUAL_ACCOUNT",
	"ARTAJASA_VIRTUAL_ACCOUNT",
	"BJB_VIRTUAL_ACCOUNT",
	"BNC_VIRTUAL_ACCOUNT",
	"BNI_VIRTUAL_ACCOUNT",
	"BRI_VIRTUAL_ACCOUNT",
	"BSI_VIRTUAL_ACCOUNT",
	"CIMB_VIRTUAL_ACCOUNT",
	"HANA_VIRTUAL_ACCOUNT",
	"MANDIRI_VIRTUAL_ACCOUNT",
	"MUAMALAT_VIRTUAL_ACCOUNT",
	"PERMATA_VIRTUAL_ACCOUNT",
	"SAHABAT_SAMPOERNA_VIRTUAL_ACCOUNT",
}

var QrisChannelCode = []string{
	"QRIS",
}
