// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: payment.proto

package ppb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreatePaymentReq struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ReferenceId       string                 `protobuf:"bytes,1,opt,name=reference_id,json=referenceId,proto3" json:"reference_id,omitempty"`
	ChannelCode       string                 `protobuf:"bytes,2,opt,name=channel_code,json=channelCode,proto3" json:"channel_code,omitempty"`
	Amount            int32                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	BuyerEmail        string                 `protobuf:"bytes,4,opt,name=buyer_email,json=buyerEmail,proto3" json:"buyer_email,omitempty"`
	BuyerMobileNumber string                 `protobuf:"bytes,5,opt,name=buyer_mobile_number,json=buyerMobileNumber,proto3" json:"buyer_mobile_number,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreatePaymentReq) Reset() {
	*x = CreatePaymentReq{}
	mi := &file_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentReq) ProtoMessage() {}

func (x *CreatePaymentReq) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentReq.ProtoReflect.Descriptor instead.
func (*CreatePaymentReq) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePaymentReq) GetReferenceId() string {
	if x != nil {
		return x.ReferenceId
	}
	return ""
}

func (x *CreatePaymentReq) GetChannelCode() string {
	if x != nil {
		return x.ChannelCode
	}
	return ""
}

func (x *CreatePaymentReq) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreatePaymentReq) GetBuyerEmail() string {
	if x != nil {
		return x.BuyerEmail
	}
	return ""
}

func (x *CreatePaymentReq) GetBuyerMobileNumber() string {
	if x != nil {
		return x.BuyerMobileNumber
	}
	return ""
}

type CreatePaymentRes struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	XenditPaymentId string                 `protobuf:"bytes,1,opt,name=xendit_payment_id,json=xenditPaymentId,proto3" json:"xendit_payment_id,omitempty"`
	Status          string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	FailureCode     string                 `protobuf:"bytes,3,opt,name=failure_code,json=failureCode,proto3" json:"failure_code,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreatePaymentRes) Reset() {
	*x = CreatePaymentRes{}
	mi := &file_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentRes) ProtoMessage() {}

func (x *CreatePaymentRes) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentRes.ProtoReflect.Descriptor instead.
func (*CreatePaymentRes) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePaymentRes) GetXenditPaymentId() string {
	if x != nil {
		return x.XenditPaymentId
	}
	return ""
}

func (x *CreatePaymentRes) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreatePaymentRes) GetFailureCode() string {
	if x != nil {
		return x.FailureCode
	}
	return ""
}

type GetPaymentByIdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentByIdReq) Reset() {
	*x = GetPaymentByIdReq{}
	mi := &file_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentByIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentByIdReq) ProtoMessage() {}

func (x *GetPaymentByIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentByIdReq.ProtoReflect.Descriptor instead.
func (*GetPaymentByIdReq) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{2}
}

func (x *GetPaymentByIdReq) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

type Action struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Descriptor_   string                 `protobuf:"bytes,2,opt,name=descriptor,proto3" json:"descriptor,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Action) Reset() {
	*x = Action{}
	mi := &file_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action) ProtoMessage() {}

func (x *Action) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action.ProtoReflect.Descriptor instead.
func (*Action) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{3}
}

func (x *Action) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Action) GetDescriptor_() string {
	if x != nil {
		return x.Descriptor_
	}
	return ""
}

func (x *Action) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ChannelProperties struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DisplayName      string                 `protobuf:"bytes,1,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	ExpiresAt        *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	SuccessReturnUrl string                 `protobuf:"bytes,3,opt,name=success_return_url,json=successReturnUrl,proto3" json:"success_return_url,omitempty"`
	FailureReturnUrl string                 `protobuf:"bytes,4,opt,name=failure_return_url,json=failureReturnUrl,proto3" json:"failure_return_url,omitempty"`
	CancelReturnUrl  string                 `protobuf:"bytes,5,opt,name=cancel_return_url,json=cancelReturnUrl,proto3" json:"cancel_return_url,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ChannelProperties) Reset() {
	*x = ChannelProperties{}
	mi := &file_payment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelProperties) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelProperties) ProtoMessage() {}

func (x *ChannelProperties) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelProperties.ProtoReflect.Descriptor instead.
func (*ChannelProperties) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{4}
}

func (x *ChannelProperties) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *ChannelProperties) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *ChannelProperties) GetSuccessReturnUrl() string {
	if x != nil {
		return x.SuccessReturnUrl
	}
	return ""
}

func (x *ChannelProperties) GetFailureReturnUrl() string {
	if x != nil {
		return x.FailureReturnUrl
	}
	return ""
}

func (x *ChannelProperties) GetCancelReturnUrl() string {
	if x != nil {
		return x.CancelReturnUrl
	}
	return ""
}

type GetPaymentByIdRes struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PaymentRequestId  string                 `protobuf:"bytes,1,opt,name=payment_request_id,json=paymentRequestId,proto3" json:"payment_request_id,omitempty"`
	RequestAmount     int32                  `protobuf:"varint,2,opt,name=request_amount,json=requestAmount,proto3" json:"request_amount,omitempty"`
	ChannelCode       string                 `protobuf:"bytes,3,opt,name=channel_code,json=channelCode,proto3" json:"channel_code,omitempty"`
	ChannelProperties *ChannelProperties     `protobuf:"bytes,4,opt,name=channel_properties,json=channelProperties,proto3" json:"channel_properties,omitempty"`
	Actions           []*Action              `protobuf:"bytes,5,rep,name=actions,proto3" json:"actions,omitempty"`
	Status            string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	FailureCode       string                 `protobuf:"bytes,7,opt,name=failure_code,json=failureCode,proto3" json:"failure_code,omitempty"`
	Created           *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created,proto3" json:"created,omitempty"`
	Updated           *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated,proto3" json:"updated,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetPaymentByIdRes) Reset() {
	*x = GetPaymentByIdRes{}
	mi := &file_payment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentByIdRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentByIdRes) ProtoMessage() {}

func (x *GetPaymentByIdRes) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentByIdRes.ProtoReflect.Descriptor instead.
func (*GetPaymentByIdRes) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{5}
}

func (x *GetPaymentByIdRes) GetPaymentRequestId() string {
	if x != nil {
		return x.PaymentRequestId
	}
	return ""
}

func (x *GetPaymentByIdRes) GetRequestAmount() int32 {
	if x != nil {
		return x.RequestAmount
	}
	return 0
}

func (x *GetPaymentByIdRes) GetChannelCode() string {
	if x != nil {
		return x.ChannelCode
	}
	return ""
}

func (x *GetPaymentByIdRes) GetChannelProperties() *ChannelProperties {
	if x != nil {
		return x.ChannelProperties
	}
	return nil
}

func (x *GetPaymentByIdRes) GetActions() []*Action {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *GetPaymentByIdRes) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetPaymentByIdRes) GetFailureCode() string {
	if x != nil {
		return x.FailureCode
	}
	return ""
}

func (x *GetPaymentByIdRes) GetCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.Created
	}
	return nil
}

func (x *GetPaymentByIdRes) GetUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.Updated
	}
	return nil
}

var File_payment_proto protoreflect.FileDescriptor

const file_payment_proto_rawDesc = "" +
	"\n" +
	"\rpayment.proto\x12\n" +
	"payment.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc1\x01\n" +
	"\x10CreatePaymentReq\x12!\n" +
	"\freference_id\x18\x01 \x01(\tR\vreferenceId\x12!\n" +
	"\fchannel_code\x18\x02 \x01(\tR\vchannelCode\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x05R\x06amount\x12\x1f\n" +
	"\vbuyer_email\x18\x04 \x01(\tR\n" +
	"buyerEmail\x12.\n" +
	"\x13buyer_mobile_number\x18\x05 \x01(\tR\x11buyerMobileNumber\"y\n" +
	"\x10CreatePaymentRes\x12*\n" +
	"\x11xendit_payment_id\x18\x01 \x01(\tR\x0fxenditPaymentId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12!\n" +
	"\ffailure_code\x18\x03 \x01(\tR\vfailureCode\"2\n" +
	"\x11GetPaymentByIdReq\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\"R\n" +
	"\x06Action\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1e\n" +
	"\n" +
	"descriptor\x18\x02 \x01(\tR\n" +
	"descriptor\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\"\xf9\x01\n" +
	"\x11ChannelProperties\x12!\n" +
	"\fdisplay_name\x18\x01 \x01(\tR\vdisplayName\x129\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12,\n" +
	"\x12success_return_url\x18\x03 \x01(\tR\x10successReturnUrl\x12,\n" +
	"\x12failure_return_url\x18\x04 \x01(\tR\x10failureReturnUrl\x12*\n" +
	"\x11cancel_return_url\x18\x05 \x01(\tR\x0fcancelReturnUrl\"\xae\x03\n" +
	"\x11GetPaymentByIdRes\x12,\n" +
	"\x12payment_request_id\x18\x01 \x01(\tR\x10paymentRequestId\x12%\n" +
	"\x0erequest_amount\x18\x02 \x01(\x05R\rrequestAmount\x12!\n" +
	"\fchannel_code\x18\x03 \x01(\tR\vchannelCode\x12L\n" +
	"\x12channel_properties\x18\x04 \x01(\v2\x1d.payment.v1.ChannelPropertiesR\x11channelProperties\x12,\n" +
	"\aactions\x18\x05 \x03(\v2\x12.payment.v1.ActionR\aactions\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12!\n" +
	"\ffailure_code\x18\a \x01(\tR\vfailureCode\x124\n" +
	"\acreated\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\acreated\x124\n" +
	"\aupdated\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\aupdated2\xad\x01\n" +
	"\x0ePaymentService\x12K\n" +
	"\rCreatePayment\x12\x1c.payment.v1.CreatePaymentReq\x1a\x1c.payment.v1.CreatePaymentRes\x12N\n" +
	"\x0eGetPaymentById\x12\x1d.payment.v1.GetPaymentByIdReq\x1a\x1d.payment.v1.GetPaymentByIdResBBZ@github.com/akmmp241/topupstore-microservice/payment-proto/v1;ppbb\x06proto3"

var (
	file_payment_proto_rawDescOnce sync.Once
	file_payment_proto_rawDescData []byte
)

func file_payment_proto_rawDescGZIP() []byte {
	file_payment_proto_rawDescOnce.Do(func() {
		file_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payment_proto_rawDesc), len(file_payment_proto_rawDesc)))
	})
	return file_payment_proto_rawDescData
}

var file_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_payment_proto_goTypes = []any{
	(*CreatePaymentReq)(nil),      // 0: payment.v1.CreatePaymentReq
	(*CreatePaymentRes)(nil),      // 1: payment.v1.CreatePaymentRes
	(*GetPaymentByIdReq)(nil),     // 2: payment.v1.GetPaymentByIdReq
	(*Action)(nil),                // 3: payment.v1.Action
	(*ChannelProperties)(nil),     // 4: payment.v1.ChannelProperties
	(*GetPaymentByIdRes)(nil),     // 5: payment.v1.GetPaymentByIdRes
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_payment_proto_depIdxs = []int32{
	6, // 0: payment.v1.ChannelProperties.expires_at:type_name -> google.protobuf.Timestamp
	4, // 1: payment.v1.GetPaymentByIdRes.channel_properties:type_name -> payment.v1.ChannelProperties
	3, // 2: payment.v1.GetPaymentByIdRes.actions:type_name -> payment.v1.Action
	6, // 3: payment.v1.GetPaymentByIdRes.created:type_name -> google.protobuf.Timestamp
	6, // 4: payment.v1.GetPaymentByIdRes.updated:type_name -> google.protobuf.Timestamp
	0, // 5: payment.v1.PaymentService.CreatePayment:input_type -> payment.v1.CreatePaymentReq
	2, // 6: payment.v1.PaymentService.GetPaymentById:input_type -> payment.v1.GetPaymentByIdReq
	1, // 7: payment.v1.PaymentService.CreatePayment:output_type -> payment.v1.CreatePaymentRes
	5, // 8: payment.v1.PaymentService.GetPaymentById:output_type -> payment.v1.GetPaymentByIdRes
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_payment_proto_init() }
func file_payment_proto_init() {
	if File_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payment_proto_rawDesc), len(file_payment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_payment_proto_goTypes,
		DependencyIndexes: file_payment_proto_depIdxs,
		MessageInfos:      file_payment_proto_msgTypes,
	}.Build()
	File_payment_proto = out.File
	file_payment_proto_goTypes = nil
	file_payment_proto_depIdxs = nil
}
